In [5]:
# Import dependencies

import pandas as pd
import json
import requests 
import numpy as np
import requests
from scipy.stats import linregress
import pprint as pprint
import seaborn as sns
import datetime
import matplotlib.pyplot as plt
import scipy.stats as st
import scipy.stats as sem
import random
# from api_keys import weather_api_key
# from api_keys import g_key
import time as time
#import wget as wget
random.seed(42)

In [6]:
# Reference to CSV and reading CSV into Pandas DataFrame
csv_path1 = "Resources/credits.csv"
csv_path2 = "Resources/keywords.csv"
csv_path3 = "Resources/links.csv"
csv_path4 = "Resources/links_small.csv"
csv_path5 = "Resources/movies_metadata.csv"
csv_path6 = "Resources/ratings.csv"
csv_path7 = "Resources/ratings_small.csv"


# merging final combined CSV meta file


credits_df = pd.read_csv(csv_path1)
keywords_df = pd.read_csv(csv_path2)
links_df = pd.read_csv(csv_path3)
links_small_df = pd.read_csv(csv_path4)
movies_metadata_df = pd.read_csv(csv_path5)
ratings_df = pd.read_csv(csv_path6)
ratings_small_df = pd.read_csv(csv_path7)

C:\Users\sunda\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
movies_metadata_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
movie_genres =movies_metadata_df["genres"]
movie_genres.head()

0    [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1    [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2    [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                       [{'id': 35, 'name': 'Comedy'}]
Name: genres, dtype: object

In [30]:
def extract_names(list_genres):
    list_genres = json.loads(list_genres.replace("'",'"'))

    genres_names = []
    for item in list_genres:
        
        genres_names.append(item['name'])
    return ",".join(genres_names)

In [29]:
extract_names(movie_genres[0])

'Animation, Comedy, Family'

In [33]:
movie_genres.apply(extract_names)

0         Animation,Comedy,Family
1        Adventure,Fantasy,Family
2                  Romance,Comedy
3            Comedy,Drama,Romance
4                          Comedy
                   ...
45461                Drama,Family
45462                       Drama
45463       Action,Drama,Thriller
45464
45465
Name: genres, Length: 45466, dtype: object

In [23]:
#test = '[{"id": 16, "name": "Animation"}]'
test=movie_genres[0].replace("'",'"')
json.loads(test)

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [36]:
movies_metadata_df["genres"] =movie_genres.apply(extract_names)
movies_metadata_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"Animation,Comedy,Family",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"Adventure,Fantasy,Family",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"Romance,Comedy",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"Comedy,Drama,Romance",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,Comedy,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [56]:
movie_collections_df=movies_metadata_df["belongs_to_collection"]
movie_collections.head()

0    {'id': 10194, 'name': 'Toy Story Collection', ...
1                                                  NaN
2    {'id': 119050, 'name': 'Grumpy Old Men Collect...
3                                                  NaN
4    {'id': 96871, 'name': 'Father of the Bride Col...
Name: belongs_to_collection, dtype: object

In [57]:
movie_genres_json='movie_genres_data.json'
movie_genres_json=pd.read_json('movie_genres_json.json', orient='split')

ValueError: Expected object or value

In [58]:
keyword1=[]
keyword2=[]
keyword3=[]
keyword4=[]
keys = movie_collections(keywords)

for key in keys:
 
        words = key
        words = ast.literal_eval(words)
        
        try:
            words1 = words[0]['name']
        except:
            words1 ='null'
            
        try:
            words2 = words[1]['name']
        except:
            words2 ='null'
            
        try:
            words3 = words[2]['name']
        except:
            words3 ='null'
            
        try:
            words4 = words[3]['name']
        except:
            words3 ='null'
            
        keyword1.append(words1)
        keyword2.append(words2)
        keyword3.append(words3)
        keyword4.append(words4)
        
keywords ={
        
        'keyword1':keyword1,
        'keyword2':keyword2,
        'keyword3':keyword3,
        'keyword4':keyword4
    }
movie_collections_df = pd.DataFrame(keywords)
movie_collections_df.head()

TypeError: 'Series' object is not callable